// examples/vue/src/App.vue
<script setup lang="ts">
import { GreeterToken } from './di/container.js';
import { useService } from './di/plugin.js';

const greeter = useService(GreeterToken);
const message = greeter.greet('Vue');
</script>

<template>
  <main>
    <h1>TinyDI + Vue</h1>
    <p>{{ message }}</p>
  </main>
</template>

// examples/react/src/App.tsx
import type { ReactNode } from 'react';
import { GreeterToken } from './di/container.js';
import { useService } from './di/DIProvider.js';

export function App(): ReactNode {
  const greeter = useService(GreeterToken);

  return (
    <main>
      <h1>TinyDI + React</h1>
      <p>{greeter.greet('React')}</p>
    </main>
  );
}
